-- V1: initial user-service schema (issue #17, ARCHITECTURE.md §3.5)
-- UUIDs are generated by the application (JPA GenerationType.UUID), so no
-- database-side default is needed on users.id.

CREATE TABLE users (
    id                  UUID PRIMARY KEY,
    username            VARCHAR(50)  NOT NULL,
    email               VARCHAR(255) NOT NULL,
    password_hash       VARCHAR(100) NOT NULL,
    role                VARCHAR(20)  NOT NULL,
    enabled             BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_locked  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP    NOT NULL,
    last_login          TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);

CREATE TABLE favorites (
    id        BIGSERIAL PRIMARY KEY,
    user_id   UUID      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    movie_id  BIGINT    NOT NULL,
    added_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_favorites_user_movie UNIQUE (user_id, movie_id)
);

CREATE TABLE watchlist_items (
    id        BIGSERIAL PRIMARY KEY,
    user_id   UUID      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    movie_id  BIGINT    NOT NULL,
    added_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_watchlist_user_movie UNIQUE (user_id, movie_id)
);

CREATE TABLE refresh_tokens (
    id          BIGSERIAL PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMP   NOT NULL,
    created_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);

-- List queries are always per-user, newest first.
CREATE INDEX idx_favorites_user       ON favorites (user_id, added_at DESC);
CREATE INDEX idx_watchlist_user       ON watchlist_items (user_id, added_at DESC);
CREATE INDEX idx_refresh_tokens_user  ON refresh_tokens (user_id);
